//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tetris.rc
//
#define IDR_MENU1                       101
#define IDR_MENU                        101
#define IDI_IC                          102
#define IDD_ABOUT                       105
#define ID_GAME_NEW                     40001
#define ID_GAME_EXIT                    40002
#define ID_HELP_ABOUT                   40003
#define ID_LEVEL_LEVEL1                 40007
#define ID_LEVEL_LEVEL2                 40008
#define ID_LEVEL_LEVEL3                 40009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
